### ISSUE TITLE
Error: Accessing object of type * which has been invalidated or deleted

### ISSUE THREAD

**Issue by jtparrett** [lolatravel/realm-react-redux#22]
When rendering a collection, and then deleting an item from the collection, the following error is received:

`Error: Accessing object of type programmes which has been invalidated or deleted`

This error makes sense, as it's attempting to render an item which doesn't exist anymore. But shouldn't the realmConnect HOC trigger a re-render after the delete so the item is no longer in the collection?

Looking for a solution around this!

Thanks 😄

**Comment by lamflam** [comment]
@jtparrett Thank you for reporting this, I agree that `realmConnect` should be re-rendering here. The queries passed to the `mapQueriesToProps` use [Realm's snapshots](https://realm.io/docs/javascript/2.25.0/api/Realm.Collection.html#snapshot), which should replace the element with `null` in the list when it has been deleted if it is a top level object in the list. If it is a nested object, the items will still be updated immediately, before `realmConnect` can re-render. If this is the case, I'm not sure if there's anything this library can do to mitigate since that is how Realm works internally, but I can look into it.

Are you accessing nested objects and is it a nested objected that is being deleted in this case? Can you post some sample code that will recreate this issue?
